### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by studentutu** [Razenpok/Razensoft.Mediator#1]
Please add a few examples on how to use it.
Thank you for all of the efforts!

**Comment by razenpok** [comment]
Thank you for your interest in this project, but I don't think I'll be able to provide comprehensive examples yet for several reasons:

- Currently, I'm using it exclusively in my workplace and it's still under the process of fleshing out. I'll probably ditch some of the APIs and change other ones, so it doesn't make much sense to document it as is.
- Apart from that, it is based on a non-conventional (in Unity community at least) [Vertical Slices](https://jimmybogard.com/vertical-slice-architecture/) architecture. It is an extension of [Clean Architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) and you can watch a primer video [here](https://www.youtube.com/watch?v=SUiWfhAhgQw). The problem with the non-conventionality of this approach is that a simple set of examples won't do much - there needs to be a whole "what dis 🧐" introduction into how this translates into the Unity environment.

So, until then, you can read those articles, watch that video and try to figure this approach out by yourself 😉

**Comment by razenpok** [comment]
Still, if you need some guidance on this topic - I can answer your questions to the best of my ability

**Comment by studentutu** [comment]
simple web request, guard case  and after it some sort of sort - would be enough. Just a simple example will do the job. Just one. 
@Razenpok  Please!

**Comment by razenpok** [comment]
Okay, fine

```csharp
public class PurchaseArmorUpgradeButton : MonoBehaviour
{
    [SerializeField] private Button _button;
    [SerializeField] private int _id;

    private void Start()
    {
        _button.onClick.AddListener(OnClicked);
    }

    private void OnClicked()
    {
        var isSuccess = InputMediator.Send(new Command{ Id = _id });
        if (isSuccess)
        {
            SpawnSomeFancyParticlesOrWhatever();
        }
        else
        {
            ShowNotEnoughMoneyMessage();
        }
    }

    public class Command : IRequest<bool>
    {
        public int Id { get; set; }
    }

    public class CommandHandler : InputRequestHandler<Command, bool>
    {
        private readonly Player _player;
        private readonly Analytics _analytics;

        public CommandHandler(Player player, Analytics analytics)
        {
            _player = player;
            _analytics = analytics;
        }

        protected override bool Handle(Command command)
        {
            _analytics.PurchaseArmorUpgradeClicked();
            if (!_player.CanPurchaseArmorUpgrade(command.Id))
            {
                return false;
            }

            _player.PurchaseArmorUpgrade(command.Id);
            _analytics.PurchaseArmorUpgradeBought();
            return true;
        }
    }
}
```

This is probably not what you expected

This is not a web-related library. Naming is hard, and `Request` is not a web request or something like that. Requests in this library are used for messaging between Unity logic and application logic (`PurchaseArmorUpgradeButton` makes a request to `CommandHandler`). Again, I recommend first watching [that primer video first](https://www.youtube.com/watch?v=SUiWfhAhgQw) if you want to understand what's going on in this code snippet.

**Comment by studentutu** [comment]
also, can request and command live in different assemblies? And which assemblies are being scanned for RequestHandlers?
Additional: to chain RequestHandlers - we will need to create another command and propagate result of Handler in InputMediator.Send(CommandFromPreviousResultHandler), correct?

**Comment by razenpok** [comment]
> can request and command live in different assemblies?

Yes, requests can live anywhere. It just doesn't make much sense to separate them from their handlers. The whole point of vertical slices is that code that changes together should live together. This helps greatly with the complexity which arises with the introduction of separate layers.

> And which assemblies are being scanned for RequestHandlers?

None of the assemblies are scanned automatically. Currently, the implementation of `InputMediator` is up to a programmer. It's not that difficult: just check the types in the assembly and instantiate the proper handler manually or with your fancy DI container, whatever.

> Additional: to chain RequestHandlers - we will need to create another command and propagate result of Handler in InputMediator.Send(CommandFromPreviousResultHandler), correct?

I never had a use case where I would need to chain handlers, what's yours?

**Comment by studentutu** [comment]
> > Additional: to chain RequestHandlers - we will need to create another command and propagate result of Handler in InputMediator.Send(CommandFromPreviousResultHandler), correct?
> 
> I never had a use case where I would need to chain handlers, what's yours?

Simple get request with Id, than make DateTime ordering sort, then optionally make another "custom" sort of target data.

Direct Example : 
Take tickets from HelpDesk, 
Sort them on the date of creation (possibly even on Priority Level),
After it sort them for the "Location".
After all of that -  optional sort on "Facility Name/Floor/Device"

As you see, It is a complex query - for business use - and it does require more setup and even caching. Also, I should mention that we are using tokens, which needs to be refreshed once in a while, which introduces another direct intermediate query for all subsequent queries. 

How would you approach it in a vertical slice fashion? 

Right now we are using a simple repository, with async AuthService - which is constantly checked on each query.

**Comment by razenpok** [comment]
The token part is the implementation detail of your API client, it's not a handler's concern. Just create a HelpDeskClient class that handles it.

The complex query part should be wholly inside the handler. I don't see any reason to split it into several commands. You have two options here: if HelpDesk API allows you to pass the query parameters then just do that, otherwise do the sorting and filtering in the handler.

The caching part is more tricky since it can be done either on the side of your UI or on the side of your infrastructure (either embed it into HelpDeskClient or create a separate caching service). Anyway, it's not a handler's concern - delegate it somewhere.

**Comment by studentutu** [comment]
Many thanks, could you update your repository with this example? I will close this issue.

**Comment by razenpok** [comment]
Sure thing 👌
